Apt/urls.py
from Apt.views import AptListView, CreateApt, UpdateApt, DeleteApt, DetailApt
from django.conf.urls import url

urlpatterns = [
    url(r'^list/(?P<pk>\d+)/$', AptListView.as_view(), name='list'),
    url(r'^detail/(?P<pk>\d+)/$', DetailApt.as_view(), name='detail'),
    url(r'^create/(?P<pk>\d+)/$', CreateApt.as_view(), name='create'),
    url(r'^update/(?P<aptBuilding_pk>\d+)/(?P<pk>\d+)/$', UpdateApt.as_view(), name='update'),
    url(r'^delete/(?P<aptBuilding_pk>\d+)/(?P<pk>\d+)/$', DeleteApt.as_view(), name='delete'),
]

Owner/urls.py
from django.conf.urls import url, include
from Owner.views import RegisterOwner, ListViewOwner

urlpatterns = [
    url(r'^register/$', RegisterOwner.as_view(), name='register'),
    url(r'^main/$', ListViewOwner.as_view(), name='main'),
    url(r'^aptBuilding/', include('AptBuilding.urls', namespace='apt-building')),
    url(r'^apt/', include('Apt.urls', namespace='apt')),

]

RP/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from RP.views import Redirect, Home

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^$', Home.as_view(), name='home'),
    url(r'^check-user-type/$', Redirect.as_view(), name='check-user-type'),
    url(r'^register/$', TemplateView.as_view(template_name='register.html'), name='register'),

    url(r'^owner/', include('Owner.urls', namespace='owner')),
    url(r'^renter/', include('Renter.urls', namespace='renter')),
    url(r'^worker/', include('Worker.urls', namespace='worker')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Apt/models.py
from django.db import models
from AptBuilding.models import AptBuilding


class Apt(models.Model):
    aptBuilding = models.ForeignKey(AptBuilding)
    number = models.IntegerField(default=0)
    allow_smocking = models.BooleanField(default=False)
    room_num = models.IntegerField(default=4)

    def __str__(self):
        return "Apt num: " + str(self.number)

Apt/forms.py
from django import forms

from Apt.models import Apt
from AptBuilding.models import AptBuilding


class AptForm(forms.ModelForm):
    class Meta:
        model = Apt
        fields = '__all__'
        exclude = ('aptBuilding', )

Apt/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from Apt.forms import AptForm
from Apt.models import Apt
from AptBuilding.models import AptBuilding


class AptListView(LoginRequiredMixin, ListView):
    template_name = 'Apt/list.html'

    def get_context_data(self, **kwargs):
        context = super(AptListView, self).get_context_data(**kwargs)
        aptBuilding = AptBuilding.objects.get(id=self.kwargs['pk'])
        context['aptBuilding'] = aptBuilding
        context['Apt'] = Apt.objects.filter(aptBuilding=aptBuilding)
        return context

    def get_queryset(self):
        return User.objects.all()


class DetailApt(LoginRequiredMixin, DetailView):
    template_name = 'Apt/detail.html'

    def get_context_data(self, **kwargs):
        context = super(DetailApt, self).get_context_data(**kwargs)
        context['Apt'] = Apt.objects.get(id=self.kwargs['pk'])
        return context

    def get_queryset(self):
        return Apt.objects.all()


class CreateApt(LoginRequiredMixin, CreateView):
    template_name = 'Apt/create.html'
    form_class = AptForm

    def form_valid(self, form):
        post = form.save(commit=False)
        post.aptBuilding = AptBuilding.objects.get(id=self.kwargs['pk'])
        post.save()
        return self.get_success_url()

    def get_success_url(self, **kwargs):
        return redirect(reverse('owner:apt:list', kwargs={'pk' : self.kwargs['pk']}))


class UpdateApt(LoginRequiredMixin, UpdateView):
    template_name = 'Apt/update.html'
    model = Apt
    form_class = AptForm
    success_message = "Updated Successfully"

    def get_success_url(self, **kwargs):
        return reverse('owner:apt:list', kwargs={'pk' : self.kwargs['aptBuilding_pk']})


class DeleteApt(LoginRequiredMixin, DeleteView):
    template_name = 'Apt/delete.html'
    model = Apt

    def get_success_url(self, **kwargs):
        return reverse('owner:apt:list', kwargs={'pk' : self.kwargs['aptBuilding_pk']})

Apt/templates/Apt/create.html
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Create">
</form>

Apt/templates/Apt/delete.html
<form action="" method="POST">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>

Apt/templates/Apt/detail.html
<h2> Apt information </h2>
<a href="{% url 'home' %}"> Home </a>
<a href="{% url 'owner:main' %}"> My main page </a><br>

Apt num: {{ Apt.number }}

{% if Apt.allow_smocking  %}
    <p> Smocking is allowed in this apts</p>
{% else %}
        <p> Smocking is not allowed in this apts</p>
{% endif %}
This apt has {{ Apt.room_num }} rooms

Apt/templates/Apt/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
    <body>
        <a href="{% url 'owner:main'%}"> Back to AptBuilding </a><br>
        <h1> Add your Apt </h1>
        <a href="{% url 'owner:apt:create' pk=aptBuilding.pk %}"> Add Here </a><br>
        {% for apt in Apt %}
            {{ apt }}
            <a href="{% url 'owner:apt:update' pk=apt.pk aptBuilding_pk=aptBuilding.pk %}"> Update </a>
            <a href="{% url 'owner:apt:delete' pk=apt.pk aptBuilding_pk=aptBuilding.pk %}"> Delete </a>
            <br>
            {% empty %}
            <h2> There is no apts for this building </h2>
        {% endfor %}
    </body>
</html>

Apt/templates/Apt/update.html
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Update">
</form>