Owner/urls.py
from django.conf.urls import url, include
from Owner.views import RegisterOwner, ListViewOwner

urlpatterns = [
    url(r'^register/$', RegisterOwner.as_view(), name='register'),
    url(r'^main/$', ListViewOwner.as_view(), name='main'),
    url(r'^aptBuilding/', include('AptBuilding.urls', namespace='apt-building')),
    url(r'^apt/', include('Apt.urls', namespace='apt')),

]

RP/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from RP.views import Redirect, Home

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^$', Home.as_view(), name='home'),
    url(r'^check-user-type/$', Redirect.as_view(), name='check-user-type'),
    url(r'^register/$', TemplateView.as_view(template_name='register.html'), name='register'),

    url(r'^owner/', include('Owner.urls', namespace='owner')),
    url(r'^renter/', include('Renter.urls', namespace='renter')),
    url(r'^worker/', include('Worker.urls', namespace='worker')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

RP/views.py
from django.contrib.auth.models import User
from django.shortcuts import redirect
from django.views.generic import ListView

from Apt.models import Apt
from AptBuilding.models import AptBuilding
from Owner.models import Owner
from Renter.models import Renter


class Redirect(ListView):

    def render_to_response(self, context, **response_kwargs):

        # if the user is renter, then send him to the renter page.
        if Renter.objects.filter(user=self.request.user).exists():
            return redirect('renter:main')

        # if the user is owner, then send him to the owner page.
        elif Owner.objects.filter(user=self.request.user).exists():
            return redirect('owner:main')
        else:
            # else send him to the worker page.
            return redirect('worker:main')

    def get_queryset(self):
        return User.objects.all()


class Home(ListView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super(Home, self).get_context_data(**kwargs)
        context['Apt'] = Apt.objects.all()
        return context

    def get_queryset(self):
        return User.objects.all()

RP/templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

RP/templates/home.html
<!-- templates/home.html-->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!<br>

    <a href="{% url 'owner:main' %}"> My main page </a>
  <p>
      <a href="{% url 'logout' %}">logout</a>
  </p>
    <h2> I have access to data.. </h2>
    {% for apt in Apt %}
        <a href="#">{{ apt }}</a><br>
    {% endfor %}

{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">login</a><br>
  <a href="{% url 'register' %}"> Create an account </a>
{% endif %}
{% endblock %}

RP/templates/register.html
<a href="{% url 'owner:register' %}"> Create account for Owner </a><br>
<a href="{% url 'renter:register' %}"> Create account for Renter </a><br>
<a href="{% url 'worker:register' %}"> Create account for Worker </a><br>

RP/templates/testHTML.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>

</head>

<body>
        <form method="POST">
            {% csrf_token %}
            <h2 class="sr-only">Login Form</h2>

            <div class="illustration">
                <i class="icon ion-ios-locked-outline"></i>
            </div>

            <div class="form-group">
                <input class="form-control" name="username" placeholder="Username">
            </div>

            <div class="form-group">
                <input class="form-control" type="password" name="password" placeholder="Password">
            </div>

            <div class="form-group">
                <button class="btn btn-primary btn-block" type="submit">Log In</button>
            </div>
            <a href="{% url 'register' %}" class="forgot">Create an Account</a>
        </form>
</body>

</html>